kubernetes-csi/external-attacher

cmd/csi-attacher/main.go
pkg/connection/connection.go
pkg/connection/connection_test.go
pkg/controller/framework_test.go

PluginCapability update for external-attacher
/cc @saad-ali @jsafrane

PluginCapability update for external-attacher

---

pkg/connection/util.go
pkg/controller/csi_handler_test.go

Fixes https://github.com/kubernetes-csi/external-attacher/issues/34

Use attributes field instead of annotations.

---

pkg/connection/connection.go
pkg/connection/connection_test.go
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go

Pass secrets from secretRef in PV to Attach and Detach calls.
Fixes: #32

Add support for ControllerPublishSecrets

---

Makefile
cmd/csi-attacher/main.go

Fixes: #43 
`make` does:
```
go build -a -ldflags '-X main.version=v0.2.0-12-gc8c6307-dirty -extldflags "-static"' -o ./bin/csi-attacher ./cmd/csi-attacher
```
And then:
```sh
$ bin/csi-attacher -version
bin/csi-attacher v0.2.0-12-gc8c6307-dirty
```
It shows git commit even when current head == some tag. I left it there to be able distinguish different builds when we force-retag something.
@lpabon @sbezverk PTAL
This should go to every CSI binary eventually.

Add -version argument to show version.

---

.travis.yml
README.md
cmd/csi-attacher/leader.go
cmd/csi-attacher/main.go
deploy/kubernetes/deployment.yaml

External attacher can now run in Deployments. One attacher per driver is active, others are standby to simplify the implementation.
It must be explicitly enabled - it needs namespace for a config map where the leader election is stored.
Fixes: #46

Add leader election.

---

cmd/csi-attacher/main.go
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go

This is PR #52 plus tests
Fixes #51

Add a timeout to attach and detach calls

---

Gopkg.lock
Gopkg.toml
vendor/k8s.io/client-go/Godeps/Godeps.json

This PR updates the Gopkg.yaml file to point to the kubernetes-1.12.0
tag because content on the release-1.12 branch could be changing over time.

Set dependency based on a tag kubernetes-1.12.0

---

deploy/kubernetes/deployment.yaml
deploy/kubernetes/rbac.yaml

Splitting out the RBAC definitions into a separate file has the
advantage that it can be used as-is without editing in other
deployments. For example, the Kubernetes E2E test uses this file.

deploy: split out RBAC definitions

---

pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go
pkg/controller/trivial_handler_test.go
pkg/controller/util.go

So the node / CSINodeInfo object can be deleted and detach continutes to work.
Fixes: #83

Store NodeID in annotation

---

deploy/kubernetes/rbac.yaml

The files worked fine in automated testing, but kubectl complains
about the missing apiGroup.

rbac: fix kubectl validation error

---

cmd/csi-attacher/main.go
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go
pkg/controller/trivial_handler_test.go

Mitigation around https://github.com/kubernetes/kubernetes/issues/71052, which is causing CSI e2e test failures in https://github.com/kubernetes/kubernetes/issues/70760.
/assign @msau42 
/cc @davidz627 @saad-ali

Temporarily calling CSINodeInfo API directly instead of using a lister

---

cmd/csi-attacher/main.go
pkg/connection/connection.go
pkg/connection/connection_test.go
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go

Implement PUBLISH_READONLY capability

---

pkg/connection/connection_test.go
pkg/controller/csi_handler_test.go

initialization of nil make go-lint unhappy. Removing it via this PR.

Remove explicit `nil` error initialization.

---

Gopkg.lock
Gopkg.toml
cmd/csi-attacher/main.go
pkg/connection/connection.go
pkg/connection/connection_test.go
pkg/controller/framework_test.go
vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/protosanitizer.go
vendor/github.com/kubernetes-csi/csi-lib-utils/release-tools/LICENSE
vendor/github.com/kubernetes-csi/csi-test/driver/mock.go

This has several effects:
- `--connection-timeout` option has no effect now, `Connect()` waits forever for the driver.
- Attacher exits when driver socket is closed (i.e. driver container either dies or restarts). This makes sure that attacher can cache driver capabilities safely, as we don't expect that driver can change its capabilities while it's running.
@pohly, @msau42, PTAL

Use Connection() from util package

---

pkg/controller/util.go
pkg/controller/util_test.go

CSI has supported raw block volumes since version 0.1, and Kubernetes
since v1.9, but the external-attacher cannot attach a block volume.
When attaching a raw block volume we don't even see an error on the
external-attacher logs saying it cannot handle it, it just goes ahead
assuming it's a mount type of volume.
This patch checks the volume mode on the spec to see if it's a raw
volume or not.
The the volume mode is define and it's PVBlock we'll use the Block
access type, in any other case (undefined and Filesystem mode) we'll use
the Mount access type.

Fix #128 - Cannot attach raw block volumes

---

Gopkg.lock
Gopkg.toml
cmd/csi-attacher/main.go
pkg/attacher/attacher.go
pkg/attacher/attacher_test.go
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go
pkg/controller/trivial_handler_test.go
vendor/github.com/kubernetes-csi/csi-lib-utils/rpc/common.go

This PR makes use of the new `csi-lib-utils/rpc` package.

Refactor external-attacher to use csi-lib-utils/rpc

---

README.md
cmd/csi-attacher/main.go
doc/development.md

- documentation for users should precede documentation of internal handling
- document all command line options
- document timeout handling
- use "external-attacher" everywhere
- [fix typo in cmdline argument description]
cc @kubernetes-csi/csi-misc, I'd like to update external-provisioner with very similar information, so let's polish it here.

Rework README for 1.14

---

CHANGELOG-1.1.md

I manually filtered git log (not every PR is shown).

Add CHANGELOG for v1.1

---

cmd/csi-attacher/main.go
pkg/controller/controller.go
pkg/controller/framework_test.go

/kind feature
Adds --retry-interval-max and --retry-interval-start to the attacher parameters to allow users to limit the exponential backoff retry time for requests. 
Fixes #
```release-note
Adds --retry-interval-max and --retry-interval-start to the csi-attacher parameters to allow users to limit the exponential backoff retry time for requests.
```

Added backoff parameters to external attacher

---

cmd/csi-attacher/main.go

/kind bug
The valid leader election types are `configmaps` and `leases`, but the default value of flag `leaderElectionType` is `configmap`, which is illegal. This PR changes the default value to `configmaps`.
```release-note
The default leader election type will be `configmaps` if not specified in the command line
```

fix default leader election type

---

cmd/csi-attacher/main.go

/kind bug
Cherry pick #144 to release-1.1: fix default leader election type
Fixes #
```release-note
Fixes default leader election type to be 'configmaps'
```

Cherry pick #144 to release-1.1: fix default leader election type

---

Gopkg.lock
deploy/kubernetes/rbac.yaml
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go
pkg/controller/trivial_handler_test.go
pkg/controller/util.go

/kind feature
Use patch to replace update
Fixes #
```release-note
NONE
```

Use patch to replace update

---

Gopkg.lock
deploy/kubernetes/rbac.yaml
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go
pkg/controller/trivial_handler_test.go
pkg/controller/util.go

This reverts commit f95364717f0fb1028185e0276ba20536e941ddaa.
PATCH usage introduced in #149 needs new RBAC rules and that effectively breaks API. We don't want to bump the image to v2.0 (yet).
ddebroy @davidz627 PTAL, I think I fixed in-line attachment unit tests correctly.
@cwdsuzhou, sorry, your contribution is great, however we'd prefer to be on the safe side. We'll keep your patch around when v2.0 time comes.
/kind api-change
(?)
```release-note
NONE
```

Revert "Use patch to replace update"

---

CHANGELOG-1.2.md
README.md

/assign @ddebroy
```release-note
NONE
```

Add 1.2 changelog with notable feature of inline volume migration

---

release-tools/build.make
release-tools/prow.sh

/kind failing-test
We want to support testing under Kubernetes 1.15 and need updated rules for that. This PR also fixes the problem that the current rules reference a 1.14 deployment of "canary" images, which became problematic when making incompatible changes in the hostpath driver (driver name change).
See https://github.com/kubernetes-csi/external-provisioner/pull/313
```release-note
NONE
```

Prow update

---

pkg/controller/csi_handler.go
pkg/controller/util.go
pkg/controller/util_test.go

/kind bug
/kind failing-test
Fixes a bug where the `pvSpec` was not translated and thus didn't pick up the backwards compatibility changes made in the `pvSpec` when getting `AccessModes` in particular
/assign @msau42 @ddebroy 
/cc @leakingtapan
```release-note
Fix issue to actually translate backwards compatible access modes for CSI Migration
```

Translate PV so that the pvSpec is also translated for things like AccessModes etc

---

pkg/attacher/attacher.go
pkg/attacher/attacher_test.go
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go

Any error from ControllerUnpublish can mean that a volume could be still attached (or being detached).
/kind bug
Fixes #164
```release-note
Action required: processing of ControllerUnpublish errors has changed. CSI drivers SHOULD return success (0), when a deleted node or volume implies that the volume is detached from the node. The external attacher treats NotFound error as any other error and it assumes that the volume may still be attached to the node. Please check behavior of your CSI driver and fix it accordingly.
```
cc @kubernetes-csi/csi-misc

Fixed ControllerUnpublish error handling

---

pkg/attacher/attacher.go
pkg/attacher/attacher_test.go
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go

/kind bug
This is backport of https://github.com/kubernetes-csi/external-attacher/pull/165 into 1.2 branch.
I added extra code to interpret `NotFound` as success (i.e. a volume is considered as detached), so behavior of `NotFound` error handling is not changed in a stable branch.
```release-note
Fixed handling of ControllerUnpublish errors. The attacher will retry to ControllerUnpublish a volume after any error except for NotFound.
```
/assign @msau42

1.2: Fixed ControllerUnpublish error handling

---

pkg/connection/connection.go
pkg/connection/connection_test.go
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go

/kind bug
This is backport of https://github.com/kubernetes-csi/external-attacher/pull/165 into 1.0 branch.
I added extra code to interpret `NotFound` as success (i.e. a volume is considered as detached), so behavior of `NotFound` error handling is not changed in a stable branch.
```release-note
Fixed handling of ControllerUnpublish errors. The attacher will retry to ControllerUnpublish a volume after any error except for NotFound.
```
/assign @msau42

1.0: Fixed ControllerUnpublish error handling

---

pkg/attacher/attacher.go
pkg/attacher/attacher_test.go
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go

/kind bug
This is backport of https://github.com/kubernetes-csi/external-attacher/pull/165 into 1.1 branch.
I added extra code to interpret `NotFound` as success (i.e. a volume is considered as detached), so behavior of `NotFound` error handling is not changed in a stable branch.
```release-note
Fixed handling of ControllerUnpublish errors. The attacher will retry to ControllerUnpublish a volume after any error except for NotFound.
```
/assign @msau42

1.1: Fixed ControllerUnpublish error handling

---

README.md

/kind cleanup
Fixes: #171
```release-note
NONE
```

Fix name of retry-interval-end parameter

---

Gopkg.lock
deploy/kubernetes/rbac.yaml
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go
pkg/controller/trivial_handler_test.go
pkg/controller/util.go

/kind cleanup
This PR restores PATCH support in the external attacher. In v2.0 we can change the behavior and also the default RBAC rules that the attacher needs.
The first commit is the same as originally applied by @cwdsuzhou in #149. The second commit openly admits that the fake client / informer is imperfect and enables tests commented out by #149.
I tried to implement the fake PATCH correctly, however, applying `[]byte` patch to existing API object looks impossible.
```release-note
Action required: The external-attacher now uses PATCH HTTP method to update API objects. Please update the attacher RBAC policy to allow the attacher to `patch`  VolumeAttachments …
```

2.0 prep: Revert "Revert "Use patch to replace update""

---

README.md
cmd/csi-attacher/main.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Currently,  external-attacher has a hard coded thread count.
However, when user create lot of Pod and PVC currently.
10 thread is not enough to sync VolumeAttachment and PV or it will take 
a bit longer time than expected.
Add a configurable flag so that user can configure a suitable value according to their own cluster scale and situation.
Fixes #172 
**Does this PR introduce a user-facing …

make worker-threads configurable

---

CHANGELOG-2.0.md

Adds changelog for v2.0
```release-note
NONE
```
/assign @msau42 
I added extra note to the top about v2.0.

Add v2.0 changelog

---

cmd/csi-attacher/main.go

Exist when a driver closes its socket.
1. The attacher caches driver capabilities, which could (in theory) change
after driver restart.
2. New driver may not come up for a while and the attacher should not act
as leader during this time.
/kind cleanup
Fixes #
```release-note
The external attacher now exits when it looses connection to a CSI driver. This speeds up re-election of a new attacher leader that has connection to the driver.
```

Exit on connection loss

---

CHANGELOG-2.0.md

/kind cleanup
```release-note
NONE
```
@msau42, PTAL

Update 2.0 changelog

---

pkg/controller/controller.go
pkg/controller/csi_handler_test.go

>
/kind bug
> /kind design
> /kind flake
currently, attacher is logging the PV name which is created by other drivers, This PR
adds a check to make sure PV is created by the same driver.
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>
Fixes #194
```release-note
NONE
```

Avoid logging PV name,where PV created by other CSI

---

cmd/csi-attacher/main.go
pkg/attacher/lister.go
pkg/controller/controller.go
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go
pkg/controller/trivial_handler.go
pkg/controller/trivial_handler_test.go

Main code-paths ready for review.
Tested with one dynamically provisioned volume with the native PD CSI Driver. After detaching the volume on the cloud provider -> external-attacher logs show correct identification of state change and update of VolumeAttachment object -> external-attacher succeeds with immediate reattachment of volume.
WIP:
/kind feature
/assign @jsafrane @msau42 
```release-note
Reconciles VolumeAttachment attachment status with actual back-end volume attachment state if plugin supports LIST_VOLUMES_PUBLISHED_NODES capability.
```

Reconcile VolumeAttachment with ListVolumes Published Nodes

---

CHANGELOG-2.1.md
README.md

Update README and CHANGELOG for release 2.1
```release-note
NONE
```

Prepare release 2.1

---

cmd/csi-attacher/main.go
go.mod
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go
pkg/controller/trivial_handler_test.go
v2/README.md
v2/cmd/csi-attacher/main.go
v2/pkg/attacher/attacher.go
v2/pkg/attacher/attacher_test.go
v2/pkg/attacher/lister.go
v2/pkg/controller/controller.go
v2/pkg/controller/controller_test.go
v2/pkg/controller/csi_handler.go
v2/pkg/controller/csi_handler_test.go
v2/pkg/controller/framework_test.go
v2/pkg/controller/trivial_handler.go
v2/pkg/controller/trivial_handler_test.go
v2/pkg/controller/util.go
v2/pkg/controller/util_test.go

/kind bug
Fix go module requirements for semantic versioning
Fixes #208.
Adding Go `dep` compatibility should be decided
```release-note
Update package path to v2. Vendoring with dep depends on https://github.com/golang/dep/pull/1963 or the workaround described in v2/README.md.
```

fix: go module requirements for semantic versioning

---

cmd/csi-attacher/main.go
go.mod
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go
pkg/controller/trivial_handler_test.go
v2/README.md
v2/cmd/csi-attacher/main.go
v2/pkg/attacher/attacher.go
v2/pkg/attacher/attacher_test.go
v2/pkg/attacher/lister.go
v2/pkg/controller/controller.go
v2/pkg/controller/controller_test.go
v2/pkg/controller/csi_handler.go
v2/pkg/controller/csi_handler_test.go
v2/pkg/controller/framework_test.go
v2/pkg/controller/trivial_handler.go
v2/pkg/controller/trivial_handler_test.go
v2/pkg/controller/util.go
v2/pkg/controller/util_test.go

Backport go module requirements for semantic versioning (#209) to release-2.1 branch.
/kind bug
Fix go module requirements for semantic versioning
N/A
N/A
```release-note
Cherry pick PR #209: fix: go module requirements for semantic versioning
```

Cherry-pick to 2.1: go module requirements for semantic versioning

---

CHANGELOG-2.1.md

Update changelog before v2.1.1 release.
```release-note
NONE
```

Add changelog for 2.1.1 release

---

cmd/csi-attacher/main.go
deploy/kubernetes/rbac.yaml
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/util.go
pkg/controller/util_test.go

/kind cleanup
CSINode is in all supported Kubernetes releases, so no more Node annotation is required.
Fixes #203 
```release-note
Removed usage of annotation csi.volume.kubernetes.io/nodeid on Node objects. The external-attacher now requires Kubernetes 1.14 with feature gate CSINodeInfo enabled.
```

Removed dependency on node annotation in favor of CSINode resource

---

pkg/controller/controller.go
pkg/controller/csi_handler_test.go

/kind bug
When a `PersistentVolume` gets deleted the external-attacher should consider it in case it has previously added its finalizer to it. Otherwise (for create/update operations), it can continue to only consider it if `.spec.csi != nil`.
Fixes #217
NONE
```release-note
A bug that prevented the external-attacher from releasing its finalizer from a `PersistentVolume` object that was created using a legacy storage class provisioner has been fixed.
```

Attacher reacts for deleted PVs if finalizer is present

---

CHANGELOG-2.2.md
README.md

/assign @msau42 
Not sure about min Kubernetes version - now the attacher requires CSINodeInfo. It was beta in 1.14 and GA in 1.17. Can we assume it's enabled in 1.15 or should we raise it to 1.17?
```release-note
NONE
```

Add CHANGELOG for v2.2.0

---

README.md

It was increased by mistake. 1.17 provides all features that the external-attacher needs.
And add links to "version" definition to README

Decrease recommended version

---

README.md

It was increased by mistake. 1.17 provides all features that the external-attacher needs.
And add links to "version" definition to README

2.2:  Decrease recommended version

---

cmd/csi-attacher/main.go
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go
pkg/controller/util.go

/kind feature
This PR changes to attacher to use the GA version of the CSINode object.
Fixes #197
```release-note
Use GA version of CSINode object.
```

Use v1.CSINode in the external-attacher

---

pkg/controller/csi_handler_test.go
pkg/controller/util.go

/kind bug
The update of the VolumeAttachment version from v1beta to v1 changed its status to be a subresource. markAsDetached() updated both the status and the finalizers in a single patch, and the update to v1 blindly put in a "status" subresource restriction, causing the finalizer removal to be silently ignored. This change removes the finalizer in a second patch.
Fixes #225
```release-note
Fixed #225
```

Update VolumeAttachment.Finalizers as separate subresource in markAsDetatched

---

.prow.sh

/kind cleanup
Going forward we are using the GA version of the CSINode object. However, Kubernetes v1.16 only
contains the v1beta1 version of that object, hence we want to skip the prow job in this version.
```release-note
NONE
```

Skip prow job when on Kubernetes v1.16.

---

release-tools/SIDECAR_RELEASE_PROCESS.md
release-tools/prow.sh
release-tools/travis.yml
vendor/modules.txt

Commit summary:
0979c091 prow.sh: fix E2E suite for Kubernetes >= 1.18
3b4a2f1d prow.sh: fix installing Go for Kubernetes 1.19.0
82d108ac switch to Go 1.15
843bddca Add steps on promoting release images
```release-note
build with Go 1.15
```

master: update release-tools

---

pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go

/kind bug
This PR fixes an issue in the volume attachment reconciler. Currently, the reconciler calls a method (unconditionally) that is supposed to be called only when the corresponding volume driver implements the in-tree plugin. 
The PR also fixes a few existing broken tests.
Fixes #243
Tested the fix with csi-mock driver. The driver does not implement in-tree plugin.
Without the fix, the reconciler failed as below:
```
W0806 02:35:26.595059       1 csi_handler.go:159] Failed to repair volume handle  for driver io.kubernetes.storage.mock: could not find In-Tree driver name for CSI plugin io.kubernetes.storage.mock
```
With the fix, no such failure …

Fixes ReconcileVA for non-migratable drivers

---

README.md

Corrections in the attacher sidecar documentation

---

go.mod

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```

Bump go version to 1.15

---

go.mod
go.sum
release-tools/SIDECAR_RELEASE_PROCESS.md
release-tools/build.make
release-tools/cloudbuild.sh
release-tools/cloudbuild.yaml
release-tools/filter-junit.go
release-tools/prow.sh
release-tools/travis.yml
vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
vendor/modules.txt

Commit summary:
7100c120 Only set staging registry when running canary job
d1294628 Document new method for adding CI jobs are new K8s versions
e73c2ce5 Use staging registry for canary tests
2c098465 Add cleanup instructions to release-notes generation
0979c091 prow.sh: fix E2E suite for Kubernetes >= 1.18
3b4a2f1d prow.sh: fix installing Go for Kubernetes 1.19.0
82d108ac switch to Go 1.15
843bddca Add steps on promoting release images
1fdf2d53 cloud build: bump timeout in Prow job
5a54e67d filter-junit: Fix gofmt error
36ea4ffa filter-junit: Fix golint error
43e50d6f prow.sh: enable building arm64 image
3df86b7d cloud build: k8s-staging-sig-storage
db0c2a7d cloud build: initialize support for running commands in Dockerfile
340e082f build.make: optional inclusion of Windows in multiarch …

release-2.2: update release-tools

---

README.md
cmd/csi-attacher/main.go
deploy/kubernetes/deployment.yaml

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
**What this PR does / why we need it**: Introduces a separate flag for the HTTP endpoint serving both metrics and leader election healthcheck, as a replacement of `metrics-address`. The now deprecated `metrics-address` flag will only enable the metrics handler, whereas `http-endpoint` enables both.
Fixes #
```release-note
The `metrics-address` flag is deprecated and replaced by …
```

Introduce http-endpoint flag

---

README.md
cmd/csi-attacher/main.go

/kind feature
Similar to other sidecars, this PR adds configurable QPS and Burst as a command line option to exteral-attacher. 
Testing:
Test is to use 64 threads to create and delete pods. With different values for QPS/Burst, the DeletePod throughput varies as shown:
1. QPS=5 (default) => 2.5 ops/sec
2. QPS=25 => 4.5 ops/sec
3. QPS=100 => 4.8 ops/sec
These tests were carried out on a k8s cluster with a modified version of VMware's CSI driver for simulation. However the numbers show that an increase in QPS helps with increasing throughput. 
Fixes #
```release-note
Add configurable throughput parameters …
```

Add configurable throughput parameters for clients to API server

---

pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/controller/csi_handler.go

/kind bug
This PR removes PV external-attacher finalizer when CSIMigration is turned off. Without this change, the in-tree PV controller is not able to delete the PV object when there is no CSI driver in the cluster.
Partially Fixes # https://github.com/kubernetes-csi/external-provisioner/issues/576
This does not fix the issue if the corresponding CSI driver is uninstalled when CSI Migration is turned off. This fix is based on the assumption that CSI driver will still be around for at least a while to remove the finalizer. 
```release-note
Fix a bug where external-attacher finalizer not get lifted for …
```

Process PV finalizer for migrated PV when CSIMigration turned off

---

release-tools/prow.sh
release-tools/pull-test.sh

Squashed 'release-tools/' changes from bc0504ad..6616a6b5
[6616a6b5](https://github.com/kubernetes-csi/csi-release-tools/commit/6616a6b5) Merge [pull request #146](https://github.com/kubernetes-csi/csi-release-tools/pull/146) from pohly/kubernetes-1.21
[510fb0f9](https://github.com/kubernetes-csi/csi-release-tools/commit/510fb0f9) prow.sh: support Kubernetes 1.21
[c63c61b3](https://github.com/kubernetes-csi/csi-release-tools/commit/c63c61b3) prow.sh: add CSI_PROW_DEPLOYMENT_SUFFIX
[51ac11c3](https://github.com/kubernetes-csi/csi-release-tools/commit/51ac11c3) Merge [pull request #144](https://github.com/kubernetes-csi/csi-release-tools/pull/144) from pohly/pull-jobs
[dd54c926](https://github.com/kubernetes-csi/csi-release-tools/commit/dd54c926) pull-test.sh: test importing …

release-3.2: update release-tools

---

pkg/controller/controller.go

/kind bug
external-attacher can panic when there is a DeletedFinalStateUnknown delete event happens. This PR checks the type of obj first before type assert to VA.
Fixes #
```release-note
Fix a bug that the controller can panic crash when it receives DeletedFinalStateUnknown deletion event.
```
/cc @msau42 @jsafrane

Panic fix: Handle DeletedFinalStateUnknown in VA deletion

---

pkg/controller/controller.go

/kind bug
Fixes #
```release-note
Fix a bug that the controller can panic crash when it receives DeletedFinalStateUnknown deletion event.
```

Cherry-pick: Panic fix: Handle DeletedFinalStateUnknown in VA deletion

---

README.md
cmd/csi-attacher/main.go

/kind feature
Similar to https://github.com/kubernetes-csi/external-provisioner/pull/643, this change adds command line arguments to configure leader election parameters.
Fixes #
```release-note
Add command line arguments to configure leader election options
```

Add command line arguments to configure leader election options

---

pkg/attacher/attacher.go
pkg/attacher/lister.go

Signed-off-by: Ben Ye <ben.ye@bytedance.com>
/kind cleanup
Reuse the same CSI controller client. This provides better performance because it is cheaper to not create & gc the client every time.
Fixes #
```release-note
```

reuse same CSI controller client

---

CHANGELOG/CHANGELOG-3.2.md
CHANGELOG/CHANGELOG-3.3.md

/kind cleanup
Added changelog, as generated by
```
release-notes --debug  --discover=mergebase-to-latest --org=kubernetes-csi --repo=external-attacher --required-author="" --output CHANGELOG-3.3.md
```
```release-note
NONE
```

Add CHANGELOG for v3.3.0

---

cmd/csi-attacher/main.go
pkg/attacher/attacher.go
pkg/attacher/attacher_test.go
pkg/controller/csi_handler.go
pkg/controller/util.go
pkg/controller/util_test.go

/kind cleanup
All occurrences reported by the unused linter of golangci-lint.
```release-note
NONE
```

Clean up unused vars, funcs and types

---

release-tools/README.md
release-tools/SECURITY_CONTACTS
release-tools/SIDECAR_RELEASE_PROCESS.md
release-tools/build.make
release-tools/cloudbuild.yaml
release-tools/go-get-kubernetes.sh
release-tools/prow.sh

Squashed 'release-tools/' changes from c0a4fb1d..a6a1a797
[a6a1a797](https://github.com/kubernetes-csi/csi-release-tools/commit/a6a1a797) Merge [pull request #176](https://github.com/kubernetes-csi/csi-release-tools/pull/176) from pohly/go-1.17.3
[0a2cf636](https://github.com/kubernetes-csi/csi-release-tools/commit/0a2cf636) prow.sh: bump Go to 1.17.3
[fc29fdde](https://github.com/kubernetes-csi/csi-release-tools/commit/fc29fdde) Merge [pull request #141](https://github.com/kubernetes-csi/csi-release-tools/pull/141) from pohly/prune-replace-optional
[5b9a1e06](https://github.com/kubernetes-csi/csi-release-tools/commit/5b9a1e06) Merge [pull request #175](https://github.com/kubernetes-csi/csi-release-tools/pull/175) from jimdaga/patch-1 …

release-3.3: update release-tools

---

pkg/controller/csi_handler.go

/kind bug
Fix get nodeid from va.annotation directly
Fixes #332 
None
```release-note
```

Fix get nodeid from va.annotation directly

---

pkg/controller/controller.go
pkg/controller/controller_test.go

> /kind bug
Respect exponential backoff when attach/detach error occurs.
Fixes #337
```release-note
NONE
```

Skip processing of ManagedFields changes

---

README.md
cmd/csi-attacher/main.go
pkg/controller/controller.go
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/util.go
pkg/controller/util_test.go

The external attacher was using a hardcoded default ext4 filesystem which was applied when PV spec did not contain fstype.
As a result attacher always reported ext4 as fs_type volume capability creating interference with some CSI drivers.
This patch adds a flag to csi-attacher binary which provides users with a workaround to set their own default filesystem or simply disable the interference by using an empty string:
`
./bin/csi-attacher --default-fstype ""
`
When the flag is not used  we still use ext4, next major release will allow behavior change and we can default to "" instead preserving the argument in case it's ever needed.
/kind bug
Fixes #287 
```release-note
There is a new --default-fstype flag …
```

allow setting default fs type through command line argument

---

CHANGELOG/CHANGELOG-3.5.md

Prepare the attacher for 3.5.0 release.
```release-note
NONE
```

Add v3.5 changelog

---

README.md
cmd/csi-attacher/main.go

/kind bug
Fixes #343 
```release-note
Change Fstype default to emptyString
Action required: CSI drivers that depended on ext4 as the default need to change their deployments to explicitly set ext4.
```

Change Fstype default to emptyString from ext4

---

release-tools/KUBERNETES_CSI_OWNERS_ALIASES
release-tools/SIDECAR_RELEASE_PROCESS.md
release-tools/build.make
release-tools/cloudbuild.yaml
release-tools/filter-junit.go
release-tools/go-get-kubernetes.sh
release-tools/prow.sh
release-tools/verify-spelling.sh

Squashed 'release-tools/' changes from a6a1a797..d29a2e75
[d29a2e75](https://github.com/kubernetes-csi/csi-release-tools/commit/d29a2e75) Merge [pull request #198](https://github.com/kubernetes-csi/csi-release-tools/pull/198) from pohly/csi-test-5.0.0
[41cb70d3](https://github.com/kubernetes-csi/csi-release-tools/commit/41cb70d3) prow.sh: sanity testing with csi-test v5.0.0
[c85a63fb](https://github.com/kubernetes-csi/csi-release-tools/commit/c85a63fb) Merge [pull request #197](https://github.com/kubernetes-csi/csi-release-tools/pull/197) from pohly/fix-alpha-testing
[b86d8e94](https://github.com/kubernetes-csi/csi-release-tools/commit/b86d8e94) support Kubernetes 1.25 + Ginkgo v2
[ab0b0a3d](https://github.com/kubernetes-csi/csi-release-tools/commit/ab0b0a3d) Merge [pull request …

release-3.4: update release-tools

---

deploy/kubernetes/deployment.yaml

What type of PR is this?
/kind feature
/label release-note-none
What this PR does / why we need it:
Related to:
https://github.com/kubernetes-csi/external-snapshotter/pull/687
Switch to the new endpoint for container images. See: https://github.com/kubernetes/k8s.io/wiki/New-Registry-url-for-Kubernetes-(registry.k8s.io)
Special notes for your reviewer:
registry.k8s.io is currently a redirect to k8s.gcr.io. The change should be transparent to any pulling from k8s.gcr.io.
Does this PR introduce a user-facing change?:
NONE

Use registry.k8s.io for deployment

---

pkg/controller/util_test.go

gofmt 1.19 requires an empty line before `package`, otherwise it reformats the license header. Tested with go 1.19.2; rest of the files are fine.
/kind cleanup
```release-note
NONE
```

Fix gofmt for go 1.19

---

pkg/controller/util_test.go
release-tools/KUBERNETES_CSI_OWNERS_ALIASES
release-tools/prow.sh

Squashed 'release-tools/' changes from d24254f6..78c0fb71
[78c0fb71](https://github.com/kubernetes-csi/csi-release-tools/commit/78c0fb71) Merge [pull request #208](https://github.com/kubernetes-csi/csi-release-tools/pull/208) from jsafrane/skip-selinux
[36e433e2](https://github.com/kubernetes-csi/csi-release-tools/commit/36e433e2) Skip SELinux tests in CI by default
[348d4a92](https://github.com/kubernetes-csi/csi-release-tools/commit/348d4a92) Merge [pull request #207](https://github.com/kubernetes-csi/csi-release-tools/pull/207) from RaunakShah/reviewers
[1efc2724](https://github.com/kubernetes-csi/csi-release-tools/commit/1efc2724) Merge [pull request #206](https://github.com/kubernetes-csi/csi-release-tools/pull/206) from RaunakShah/update-prow …

release-4.0: update release-tools

---

.github/dependabot.yaml

Additional note for reviewer:
external-provisioner already have this github action.
https://github.com/kubernetes-csi/external-provisioner/blob/master/.github/dependabot.yaml
```release-note
NONE
```

add dependabot github action for auto dependency update

---

CHANGELOG/CHANGELOG-4.1.md
README.md

Add changelog for v4.1.0. When at it, I marked CSI migration as a GA feature, it was GA already for some CSI drivers, now it's GA for all cloud based ones.
```release-note
NONE
```

Add changelog for v4.1.0

---

pkg/controller/util_test.go
release-tools/KUBERNETES_CSI_OWNERS_ALIASES
release-tools/SIDECAR_RELEASE_PROCESS.md
release-tools/filter-junit.go
release-tools/go-get-kubernetes.sh
release-tools/prow.sh

I forgot to update release-3.5 branch in the last release-tools bump in https://github.com/kubernetes-csi/external-attacher/pull/384 / https://github.com/kubernetes-csi/external-attacher/pull/383 / https://github.com/kubernetes-csi/external-attacher/pull/382
This should fix CI in release-3.5 branch.
Squashed 'release-tools/' changes from e4dab7ff..a2171bef
[a2171bef](https://github.com/kubernetes-csi/csi-release-tools/commit/a2171bef) Merge [pull request #216](https://github.com/kubernetes-csi/csi-release-tools/pull/216) from msau42/process
[cb987826](https://github.com/kubernetes-csi/csi-release-tools/commit/cb987826) Merge [pull request #217](https://github.com/kubernetes-csi/csi-release-tools/pull/217) from msau42/owners
[a11216e4](https://github.com/kubernetes-csi/csi-release-tools/com …

release-3.5: update release-tools

---

cmd/csi-attacher/main.go
go.mod
go.sum
vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
vendor/modules.txt

/kind feature
ListVolume call generates tons of log items because by default the entirety of the grpc response body gets logged out. That consumes log space really fast and we want to limit how much can be logged in the same message.
adding a flag to optionally limit GRPC log message length to fix this issue.
Fixes #
```release-note
Logging for gRPC call can now be limited configurably with flag `--grpc-log-char-cap`
```

add option to limit grpc logging length

---

pkg/attacher/attacher_test.go

"io/ioutil" has been deprecated since Go 1.19: As of Go 1.16
Fixes #
```release-note
NONE
```

chore: remove refs to deprecated io/ioutil

---

pkg/controller/csi_handler.go

should use fmt.Errorf(...) instead of errors.New(fmt.Sprintf(...))
Fixes #
```release-note
NONE
```

chore: use fmt.Errorf(...) instead of errors.New(fmt.Sprintf(...))

---

README.md
cmd/csi-attacher/main.go
pkg/attacher/lister.go
pkg/controller/csi_handler_test.go

/kind feature
CSI spec supports MaxEntries per page, but the attacher doesn't allow to use it. This PR adds an ability to specify this parameter in the `ListVolumesRequest` object.
Fixes #461 
```release-note
Add --max-entries flag to limit ListVolumes request entries per page
```

Add max-entries flag to limit ListVolumes request entries per page

---

release-tools/contrib/get_supported_version_csi-sidecar.py
release-tools/prow.sh

Squashed 'release-tools/' changes from 4133d1df..1df23dba
1df23dba Merge pull request #230 from msau42/prow
1f92b7e7 Add ginkgo timeout to e2e tests to help catch any stuck tests
c10b6780 Merge pull request #227 from coulof/check-sidecar-supported-versions
b0555351 Header
bd0a10b6 typo
c39d73c3 Add comments
f6491af0 Script to verify EOL sidecar version
```release-note
NONE
```

Release tools update

---

.github/dependabot.yaml

/kind cleanup
Add back groups and we can use [dependabot command like ignore](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates#managing-dependabot-pull-requests-for-grouped-version-updates-with-comment-commands) to exclude packages.
Fixes #
```release-note
NONE
```

Add Back Github Groups

---

pkg/attacher/lister.go

>
> /kind design
> /kind flake
/kind bug
This PR fix the panic in the Lister when a `volume` or `status` is `nil`
Fix #502 
Since the `Status` is optional in some case, if status is nil, is it valid to return a key `VolumeId` in map with value `Status` nil?
```release-note
NONE
```

Attacher(fix): prevent panic on nil volume/status in lister

---

CHANGELOG/CHANGELOG-4.5.md

Add changelog for the next release.
I had to manually edit release-notes output, somehow it caught PRs in release-tools like https://github.com/kubernetes-csi/csi-release-tools/pull/246
cc @xing-yang @msau42 
```release-note
NONE
```

Add changelog for 4.5

---

cmd/csi-attacher/main.go

/kind bug
The same context.WithTimeout was used in different places when calling the CSI drivers in the main function. With recent changes, the code execution started taking longer and the context would hit its timeout on the `GetPluginCapabilities` driver call. For instance with when running with the azuredisk-csi-driver (I've seen this on the aws-ebs and the gcp-pd drivers too):
```
❯ k logs -c csi-attacher csi-azuredisk-controller-69fdb787c6-k59fw
I0529 12:26:30.367859       1 main.go:109] "Version" version="v4.6.0-0-gc58f4277"
I0529 12:26:30.369489       1 connection.go:234] "Connecting" address="unix:///csi/csi.sock"
I0529 12:26:31.370120       1 common.go:145] "Probing CSI driver for readiness"
I0529 …
```

Fix timeout on short CSI calls during attacher initialization

---

cmd/csi-attacher/main.go

/kind feature
If not specified explicitly, JSON encoding is used by default when talking to kube-apiserver.
For core K8s API objects like Pods, Nodes, etc., we can use protobuf encoding which reduces CPU consumption related to (de)serialization, reduces overall latency of the API call, reduces memory footprint, reduces the amount of work performed by the GC and results in quicker propagation of objects to event handlers of shared informers.
No issue is opened for that.
Standard system components of K8s default their serialization method to protobuf for some time already:
- `kube-scheduler`: [link](https://github.com/kubernetes/kubernetes/blob/d62b797c1 …

Use protobuf encoding for core K8s APIs in external-attacher

---

pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go
pkg/controller/util.go

/kind bug
Remove a finalizer on a VolumeAttachment (VA) first and then mark its state as detached (if the object still exists).
This ensures that `ControllerUnpublish` is called only once. It [won't be called](https://github.com/kubernetes-csi/external-attacher/blob/e5ae92e87bb6c3d99061ca515285c5c9e76e0414/pkg/controller/csi_handler.go#L286-L289) on VA without the finalizer, even if it has `attached: true`.
The other way around, i.e. marking the VA as detached first and removing the finalizer later, it can happen that the attacher calls `ControllerUnpublish` twice. A VA with the finalizer, `deletionTimestamp` and `attached: false` is considered as "uncertainly attached" - a previous `ControllerPublish` might have timed …

Reorder API calls after successful detach

---

cmd/csi-attacher/main.go
go.mod
pkg/attacher/attacher.go
pkg/attacher/attacher_test.go
pkg/controller/controller.go
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go
pkg/controller/trivial_handler.go
pkg/controller/util.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
**What this PR does / why we need it**: this PR seeks to update the external-attacher repo so various Go linters no longer
raise any warnings for the code. The repo should follow modern Go constructs and best practices, as well as migrate from deprecated symbols and package imports.
Fixes #
**Special notes for your reviewer**: I am happy to explain any part of my change.
**Does this PR introduce a user-facing change?**: no
```release-note
NONE
```

Address various linter (staticcheck, modernize, etc.) comments.

---

release-tools/KUBERNETES_CSI_OWNERS_ALIASES
release-tools/prow.sh

/kind cleanup
Squashed 'release-tools/' changes from 0a435bf9..5f38a907
5f38a907 Merge pull request #282 from rhrmo/update-go-1.24.6
579f6242 Update go to 1.24.6
74e066a8 Merge pull request #279 from Aishwarya-Hebbar/update-csi-prow-version
6f236be7 Update CSI prow driver version to v1.17.0
0ee55894 Merge pull request #280 from xing-yang/update_go_1.24.4
9af10153 update to go 1.24.4
f5fec3e3 Merge pull request #275 from chrishenzie/emeritus
c5d285db Remove chrishenzie from kubernetes-csi-reviewers
git-subtree-dir: release-tools
git-subtree-split: 5f38a907597230563f5e2213aea116acdd9d86bc
```release-note
NONE
```

Update release tools
