pkg/controller/framework_test.go
pkg/controller/trivial_handler_test.go

The framework is work-in-progress and will be probably extended to accomodate
CSI in some form.

Add unit tests for the controller.

---

README.md
cmd/csi-attacher/main.go
pkg/connection/connection.go
pkg/connection/connection_test.go
pkg/connection/util.go
pkg/connection/util_test.go
pkg/controller/controller.go
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go
pkg/controller/trivial_handler.go
pkg/controller/trivial_handler_test.go
pkg/controller/util.go

Added PV finalizers. Significant refactoring was needed to achieve that.

Add Pv finalizers

---

cmd/csi-attacher/main.go
pkg/connection/connection.go
pkg/connection/connection_test.go
pkg/controller/framework_test.go

Add ControllerProbe

---

pkg/connection/util.go
pkg/connection/util_test.go

fix: #30
/cc @saad-ali @jsafrane

Set FsType for VolumeCapability_MountVolume

---

pkg/connection/connection.go

Change in isFinalError func Issue 53

---

cmd/csi-attacher/main.go

10 minutes is a good start, we can increase it further when attached is
more stable.
Fixes: #55
/assign @msau42

Increase resync period.

---

Makefile

Signed-off-by: Luis Pabón <luis@portworx.com>

Update tag to 0.4.1

---

cmd/csi-attacher/leader.go
cmd/csi-attacher/main.go

This is a simple code clean PR:
Currently we run the leader election in a single goroutine and start the `CSIAttachController` in another goroutine after becoming leader.
However, as `LeaderElectionConfig` has an `OnStartedLeading` callback, we can start the `CSIAttachController` inside this callback, just like what the [k8s in-tree controllers](https://github.com/kubernetes/kubernetes/blob/2f9b65143e44895887f3d91bd019e49a4b3b7658/cmd/kube-controller-manager/app/controllermanager.go#L236) do. This can make the code more concise.

start attach controller inside OnStartedLeading callback

---

pkg/connection/connection.go
pkg/controller/controller.go
pkg/controller/trivial_handler.go
pkg/controller/util.go

Add function details in external attacher exported functions.

---

README.md

Correct markdown linter errors.

---

README.md

Adding documentation to new command line arguments introduced in previous PR #141 
Already introduced in previous PR this one just adds to the documentation
```release-note
NONE
```

Added new command line arguments to README.md

---

CHANGELOG-1.1.md

Add Changelog for 1.1.1 release
Fixes #
```release-note
NONE
```

Add changelog for 1.1.1

---

deploy/kubernetes/rbac.yaml

/kind bug
Attach will be fail when StorageClass specific parameters `csi.storage.k8s.io/controller-publish-secret-name` and `csi.storage.k8s.io/controller-publish-secret-namespace`
Fixes #88 
```release-note
None
```

update rbac for secret

---

Gopkg.lock
Gopkg.toml
vendor/k8s.io/csi-translation-lib/plugins/aws_ebs.go
vendor/k8s.io/csi-translation-lib/plugins/azure_disk.go
vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
vendor/k8s.io/csi-translation-lib/plugins/gce_pd.go
vendor/k8s.io/csi-translation-lib/plugins/in_tree_volume.go
vendor/k8s.io/csi-translation-lib/plugins/openstack_cinder.go
vendor/k8s.io/csi-translation-lib/translate.go

/kind cleanup
/kind feature
/assign @leakingtapan @msau42 @jsafrane  
/cc @ddebroy 
New CSI Migration functionality for Azure + fixes for GCE PD
```release-note
Adds CSI Migration support for Azure Disk/File, fixes for backward compatible AccessModes for GCE PD.
```

Bump version of csi-translation-lib to master to include translation lib for Azure Disk/File, updates for AWS, GCE, OpenStack

---

CHANGELOG-1.2.md

/assign @msau42 @jsafrane 
```release-note
NONE
```

Update CHANGELOG for new external attacher release

---

go.mod
go.sum
vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
vendor/modules.txt

/kind cleanup
/assign @msau42 
```release-note
NONE
```

Yank CSI Spec into the future (bump to v1.2.0)

---

README.md
cmd/csi-attacher/main.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fix typos
Fixes #
```release-note
NONE
```

Fix metrics typos

---

doc/development.md

fix incorrect link

---

cmd/csi-attacher/main.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
this is a leftover const  from the leaderelectiontype cleanup.
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>
Fixes #
```release-note
NONE
```

Remove unused leaderElectionTypeConfigMaps const

---

cmd/csi-attacher/main.go

In case the attacher is busy and its client is throttled, the leader election should proceed without any delays.
/kind bug
Fixes #241
```release-note
Use dedicated Kubernetes client for leader election that does not get throttled when the external-attacher is under heavy load.
```

Use separate client for leader election

---

cmd/csi-attacher/main.go
go.mod
pkg/attacher/attacher.go
pkg/controller/controller.go
pkg/controller/csi_handler.go
pkg/controller/csi_handler_test.go
pkg/controller/framework_test.go
pkg/controller/trivial_handler.go
pkg/controller/util.go

/kind cleanup
(?)
* Use klog2
```release-note
NONE
```

Rework to klog/v2

---

CHANGELOG/CHANGELOG-3.0.md

Fixes #
```release-note
NONE
```

Update 3.0 changelog

---

CHANGELOG-2.2.md

Add change log for 2.2.1 release
Fixes #
```release-note
NONE
```
/cc @msau42

Add change log for 2.2.1 release

---

CHANGELOG/CHANGELOG-3.0.md

Create v3.0.1 change log
Fixes #
```release-note
NONE
```
/cc @msau42

Create v3.0.1 change log

---

Dockerfile

>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```

Cherry-pick #261: Fix the failing multiarch builds

---

CHANGELOG/CHANGELOG-3.0.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```

Add changelog for v3.0.2

---

release-tools/prow.sh

Squashed 'release-tools/' changes from 5d874cce..c6a88c6e
c6a88c6e Merge pull request #113 from xing-yang/install_snapshot_controller
45ec4c69 Fix the install of snapshot CRDs and controller
git-subtree-dir: release-tools
git-subtree-split: c6a88c6ed96b939bd150472b12693252942116c7

Release tools

---

cmd/csi-attacher/main.go

Don't initialize a second CSIMetricsManager, use the one already created.
/kind bug
Inspired by kubernetes-csi/external-health-monitor#46, thanks @pohly for spotting this.
```release-note
NONE
```

Fix metrics endpoint initialization

---

cmd/csi-attacher/main.go

>
/kind bug
> /kind design
> /kind flake
```release-note
NONE
```
/assign @jsafrane @msau42

Add server listening log; fix wrong address logged in listening error

---

README.md
cmd/csi-attacher/main.go

>
> /kind bug
> /kind design
> /kind flake
```release-note
NONE
```

Documentation fixes for HTTP endpoint

---

CHANGELOG/CHANGELOG-3.1.md

Add changelog for v3.1.0
```release-note
NONE
```

Add changelog for v3.1.0

---

pkg/controller/csi_handler.go

/kind bug
When the driver is missing in the csinode, that doesn't mean we can't unmap. We should support the volume attachment node ID for unmap. For example CSI might not be running (the node could even be shut down!), so the driver would not be present, but the csi node might exist. I want the behaviour to match the csi node not existing at all; fall back to the node ID in the VA.
```release-note
NONE
```

On missing driver, fall back to volattachment ID

---

CHANGELOG/CHANGELOG-3.2.md

Add Changelog for v3.2.0
```release-note
NONE
```

Add changelog for v3.2.0

---

CHANGELOG/CHANGELOG-3.2.md

Create release-notes for v3.2.1 release
Fixes #
```release-note
none
```

Create release-notes for v3.2.1

---

CHANGELOG/CHANGELOG-3.4.md

Add CHANGELOG for v3.4
```release-note
NONE
```

Add CHANGELOG for v3.4

---

OWNERS

please see [kubernetes/community#6334](https://github.com/kubernetes/community/issues/6334)
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
What type of PR is this?   
/kind cleanup
What this PR does / why we need it:
Which issue(s) this PR fixes: 
Fixes #
Special notes for your reviewer:
Does this PR introduce a user-facing change?  
```
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```
```

Validate OWNERS files - remove sections about emeritus reviewers

---

README.md

Update container-storage-interface.md design proposals URL in README.md which was already archived in https://github.com/kubernetes/design-proposals-archive/blob/main/storage/container-storage-interface.md
Origin URL (https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/container-storage-interface.md) becomes 404.
Fixes # none
NONE
```release-note
NONE
```

Update container-storage-interface.md design proposals URL in README.md

---

CONTRIBUTING.md

Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #375

Fixes broken link CONTRIBUTING.md

---

CHANGELOG/CHANGELOG-3.5.md

Add changelog for v3.5.1
```release-note
NONE
```
cc @xing-yang @msau42 @gnufied

Add changelog for v3.5.1

---

CHANGELOG/CHANGELOG-4.2.md

Add changelog for v4.2.0 
Fixes #
```release-note
NONE
```

Add changelog for v4.2.0

---

CHANGELOG/CHANGELOG-4.4.md

Add changelog for the next release.
Fixes #
```release-note
NONE
```

Add changelog for v4.4

---

release-tools/SIDECAR_RELEASE_PROCESS.md

release-tool update

---

CHANGELOG/CHANGELOG-4.4.md

Fixes #
```release-note
NONE
```

Add changelog to v4.4.1

---

CHANGELOG/CHANGELOG-4.4.md

Add changelog for v4.4.2
Fixes #
```release-note
NONE
```

Add changelog for v4.4.2

---

CHANGELOG/CHANGELOG-4.4.md

Changelog for v4.4.3

---

release-tools/KUBERNETES_CSI_OWNERS_ALIASES
release-tools/SIDECAR_RELEASE_PROCESS.md
release-tools/generate_patch_release_notes.sh
release-tools/go-modules-update.sh
release-tools/prow.sh
release-tools/pull-test.sh

>
/kind cleanup
Squashed 'release-tools/' changes from de2fba88..dc4d0ae2
```
git subtree pull --squash --prefix=release-tools https://github.com/kubernetes-csi/csi-release-tools.git master
```
Fixes #
```release-note
N/A
```

[release-4.4] Update release tools with go version fix

---

CHANGELOG/CHANGELOG-4.4.md

Changelog for v4.4.4

---

CHANGELOG/CHANGELOG-4.5.md

Changelog for v4.5.1

---

CHANGELOG/CHANGELOG-4.6.md

Add changelog for the next release.
```release-note
NONE
```

Add changelog for v4.6

---

CHANGELOG/CHANGELOG-4.6.md

Add changelog for 4.6.1

---

CHANGELOG/CHANGELOG-4.8.md

Add changelog for release v4.8.0
```release-note
NONE
```

Add changelog 4.8.0

---

CHANGELOG/CHANGELOG-4.9.md

Add changelog for a new release.
```release-note
NONE
```

Add changelog for 4.9
